# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            hugohil
tagline:          visual coding
url:              http://hugohil.github.io
paginate:         1
baseurl:          /
author:
  name:           hugohil
  email:          hugo@soixantecircuits.fr

# Custom vars
version:          1.0.0
analytics:        UA-60055019-1
github:
  repo:           https://github.com/hugohil/hugohil.github.io